### ISSUE TITLE
Smoothness / Handwriting style selection

### ISSUE THREAD

**Issue by CasparNuel** [daledesilva/obsidian_ink#73] opened 2024-08-28 22:00 UTC
**What's your idea?**

I really like the setup of this plugin and the way it integrates into notes. The writing style this plugin "produces" does however feel a bit unnatural to me. I am unsure if this is a limitation of the drawing back-end used in the Ink plugin, or if this could be solved by exposing some parameters of the drawing back-end to the user (or perhaps provide some presets, like "smooth", "straight", "penlike", ...). These presets could even be selectable over both the draw and write function seperately.

**Why? How would it help you (or others)?**

It makes the writing experience nicer, being able to fine-tune the handwriting behaviour allows users to get an output that is more accustomed to their specific way of handwriting.

**Any examples or references you think are worth pointing out?**

I recorded a video comparing (almost) the same handwriting in Samsung Notes (native app on my tablet) and Ink in Obsidian. It is somewhat hard to show the different writing behaviour with just a screen capture, as you cannot see how the drawing interacts with the physical location of my pen tip. However, I think just from difference in appearance of the writing my point will be clear.

https://github.com/user-attachments/assets/e4be5963-6540-4c1c-bd86-e3d3e4b96fde

The difference is mainly in the fact that Ink feels more like a fountain pen being used on smooth paper, while Samsung Notes feels more like using a small point marker on a whiteboard for example. I prefer the second (completely a personal preference).

Especially in the letters "n" at the end of the word the "smoothing" in Ink becomes apparent. Samsung Notes on the other hand almost exactly "writes" where my pen passes without smoothing or straighting things out.

It would be nice if there were parameters available to tweak behaviour like this, or some presets if that is easier to implement.

**Anything else?**

I enjoy this plugin very much and would love to get its touch and feel as close to my current setup (Samsung Notes). I am very picky about writing "feel" on my tablet and I understand comparing a basically embedded webpage to a native pen-enabled app is a big ask but it would be a very big win for me if I could do all my writing in Ink in Obisidian from now on (and drop Samsung Notes completely).

Thank you for your time and effort!

**Comment by CasparNuel** [comment] 2024-08-30 10:16
I don't know if this "feel" is feasible with the drawing back-end that is used currently, but this library: (<https://gojs.net/latest/samples/FreehandDrawing.html>) feels very responsive and "draws" almost exactly in the way I am trying to describe above.

I don't know how it will behave on an iPad, but for me (Galaxy Tab S8 with standard S-Pen) the writing on that demo page feels almost 1:1 with how samsung notes in pen mode behaves, and it does not have the "smoothing delay" you have with many other drawing libraries in browser (Excalidraw for example has a minimal, but just noticeable delay between where your pen tip is and where the line is being drawn)

**Comment by daledesilva** [comment] 2024-09-02 11:20
Hi @CasparNuel Thanks for all the detail.
I've created a catch-all for the issue your experiencing [here in issue 41](https://github.com/daledesilva/obsidian_ink/issues/41).

It's essentially due to how your stylus reports what it is to the browser (The browser thinks it's a mouse). The Tldraw framework Ink uses smooths mice more (as that feels much better for mice), and smooths styluses less (Because of the reason you've described). But some stylus, like yours, don't report as styluses so the wrong smoothing gets applied.

Anyway, I have a fix in the works in the other issue thread. I'm closing this one as a result.

**Comment by daledesilva** [comment] 2024-09-02 11:23
Duplicate of #41

**Comment by daledesilva** [comment] 2024-09-02 11:23
Duplicate of #41

**Closed by daledesilva** 2024-09-02 11:23 UTC
Labels: enhancement
