### ISSUE TITLE
Writing file error: Object.hasOwn is not a function

### ISSUE THREAD

**Issue by thatBiologyStudent** [daledesilva/obsidian_ink#24] opened 2024-04-16 11:43 UTC
So I use Syncthing to keep all my vaults up to date and Synced and something weird happens:
- My PC displays writing sections fine/allows me writing
- My Samsung tablet displays writing sections fine/allows me writing
- My Matepad Shows me the header Select/Write/Erase/Lock, but instead of a canvas beneath I get the following error:

"Sorry, we encountered an error. Please refresh the Page to continue. If you keep seeing this error, you can create a Github issue or ask for help on Discord.
Error: [Empty]
Stack Trace:
TypeError: Object.hasOwn is not a function
    at Editor.updateShapes (plugin:ink:50052:58)
    at Editor.updateShape (plugin:ink:50040:10)
    at eval (plugin:ink:88639:14)
    at transaction (plugin:ink:31523:20)
    at transact (plugin:ink:31541:10)
    at Store.eval [as mergeRemoteChanges] (plugin:ink:33632:9)
    at silentlyChangeStore (plugin:ink:82720:16)
    at resizeTemplate (plugin:ink:88638:5)
    at handleMount (plugin:ink:88544:5)
    at eval (plugin:ink:82346:44)"

Resetting date/Refreshing the page wont help. 

Weird, that it only Happens to the MatePad.

**Comment by daledesilva** [comment] 2024-04-16 12:28
Thanks for copying the error in. It should be enough.
I'll have a look over the next few days.

**Comment by thatBiologyStudent** [comment] 2024-04-16 13:06
Thank you very much for the awesome work and quick response :-)

**Comment by thatBiologyStudent** [comment] 2024-05-05 22:18
Just tested it, uninstalling and Installing, and sadly, it still doesnt work

**Comment by daledesilva** [comment] 2024-05-06 11:39
Thanks for the update.
I've just dug up an old android phone and installed Obsidian on there and I've managed to reproduce this exact bug.

I've also found that while the writing files get the error above, the drawing files don't.
Is this the same for you? (You have to turn on drawing in the settings to test it).

I also don't get either showing up when embedded in markdown files, which also needs to be fixed. The above only applied when clicking on the writing and drawing files directly.

**Comment by thatBiologyStudent** [comment] 2024-05-06 12:02
Yep, can confirm, Same for me.

**Comment by CyberLynxAdmin** [comment] 2024-05-09 12:33
I can confirm that I have the same behaviour after clean installation of release 0.1.19.
Thank you for your time and effort!!

**Comment by daledesilva** [comment] 2024-05-26 11:34
This took some time to sort out but it should be fixed now in version 0.2.0 and later.
Turns out it was an issue with some unsupported CSS and Javascript in older versions of Android.

@thatBiologyStudent and @CyberLynxAdmin , it will be really helpful if you could update via BRAT and confirm this is fixed for you before I push the update live for everyone.

Thank you for reporting and discussing the issue!
Dale.

**Comment by CyberLynxAdmin** [comment] 2024-05-27 09:35
Wow!!! Confirmed!!! I have installed the 0.2.0 and it works.

The only problem I notice is the performance. The Lenovo Smart Paper has a feature called "Inking" that allows you to write anywhere. Once you finish writing with the pen, it transfers it to the open program. Unfortunately, the performance makes it difficult to use comfortably. I tried writing the letters more slowly, and it responds better.

I don't know if you can resolve this issue as well, but in any case, I personally thank you for the time you dedicate. For me, it is a must-have plugin.

**Comment by daledesilva** [comment] 2024-05-27 12:28
Thanks @CyberLynxAdmin for the confirmation 🙂
Are you able to shoot a video of the "inking" so I can understand better? Or even if you know of a video online you can send me?

**Comment by CyberLynxAdmin** [comment] 2024-05-31 09:39
@daledesilva Please feel free to ask for further clarifications if anything mentioned above is unclear.

Describe the bug
The Lenovo Smart Paper has the "Inking" feature which facilitates smooth writing or drawing in applications that do not natively support e-ink tablets. Essentially, you write on top of the application, and the "inking" function registers any information drawn by the stylus in the respective application. During the use of the plugin, performance is unfortunately the only obstacle that remains to be resolved. The performance issues you will see in the uploaded video are the same with the "inking" feature enabled or disabled. Additionally, the same performance problem exists in both writing and drawing sections, even if I open them from the "Ink" folder. 

Video or screenshots
https://github.com/daledesilva/obsidian_ink/assets/117518291/738ba37e-c0f1-4e20-bed3-a3668cdd9366


Device & OS: Lenovo Smart Paper / Android 11
Plugin version: 0.2.0
Obsidian version: 1.5.12 (134)

Additional context
I use Xodo and Adobe Acrobat for PDF annotations in combination with the "Inking" feature, and the performance is fine.

**Comment by daledesilva** [comment] 2024-05-31 15:37
It's really interesting to me that they provide the inking feature so you can draw low latency, but then don't translate that hifidelity to the underlining app.

I don't have high hopes about supporting native ereader functions from a web app (other ereaders have a similar issue), but nonetheless, I'll try and learn more about it.

I can't seem to find any information about developing for low latency stylus support for Lenovo Smart Paper. Please let me know if you come across anything.

**Comment by daledesilva** [comment] 2024-05-31 15:38
Oh. And thank you for the video. It was very clear!

**Closed** 2024-06-08 00:55 UTC
Labels: bug, planned
