### ISSUE TITLE
Undo and redo actions with keybindings or hotkeys

### ISSUE THREAD

**Issue by RookiNumbers** [daledesilva/obsidian_ink#83] opened 2024-09-20 14:37 UTC
**What's your idea?**
I would like to be able to undo and redo strokes, as with the curved arrow button in the top left, but with other keyboard inputs like ctrl+z and ctrl+y. I could then use Air Commands on my galaxy tab with my s pen to easily remove strokes without having to reach to the top left every time I make a mistake.

**Why? How would it help you (or others)?**
Quickly undo strokes

**Any examples or references you think are worth pointing out?**
I'm not sure. I have set this up via Tasker in my other drawing apps so consistency would be really cool. I love the implementation of the Ink plugin and I wouldn't want to have to switch to Excalidraw or stuff like that...

**Anything else?**
Keep up the amazing work!

**Comment by daledesilva** [comment] 2024-12-05 12:29
Thanks for posting.
Closing as duplicate of #28 
(Which is planned to be addressed in the next few versions if possible)

**Closed by daledesilva** 2024-12-05 12:29 UTC
Labels: enhancement
