### ISSUE TITLE
Unable to insert handwriting section

### ISSUE THREAD

**Issue by tripp396** [daledesilva/obsidian_ink#14] opened 2024-04-04 13:50 UTC
First, love the idea of this plugin. Something I’ve wanted for a while.

Here is the issue I am facing. When inserting a new handwriting section, nothing happens. I assumed there was some weird plugin compatibility issue so I started a brand new vault with no other plugins except BRAT, slash commander, and ink. Still having the same issue. Behavior is I click to add the section and it just goes back to my normal cursor.

I should have the latest version as I just installed this morning. Told BRAT to update it and restarted obsidian and still not able to do it.

Let me know if there are logs I can grab or anything else that can help.

**Comment by anchoo2kewl** [comment] 2024-04-04 18:44
I have the same issue! Tried on my Mac and the iPad! The slash command shows them but does not do anything when invoked!

**Comment by ichmoimeyo** [comment] 2024-04-04 18:49
I am having the same issue.

I opened brand new totally empty different vaults on an Android phone, a Linux Crostini Chromebook and a Windows 11 PC.

I installed Ink manually by creating an "Ink" folder in the .obsidian/plugins folder and  then downloading into it:
main.js
manifest.json
styles.jss

Using both ctrl+p and the slash command I tried ...

Insert new handwriting section
Insert existing handwriting section

... neither of them worked in the current 0.1.15 or previous 0.1.1

However in the original 0.1.0 I could get it to work using 

https://github.com/daledesilva/obsidian_ink/issues/9#issue-2218564520

> "Insert New..." Creates the block but does not show it in the note.
> Immediately doing "Insert Existing..." shows that the block was created, and selecting it makes it show up in the UI

So I have reverted to the original 0.1.0 for the time being so that I can  continue using INK.

@daledesilva - a huge thanks for developing this :)

**Comment by daledesilva** [comment] 2024-04-04 20:54
Thanks for reporting everyone. For anyone that hasn't already, please go to the community plugins tab in settings and let me know the version of ink you're on just to be sure.

Also please let me know the version of obsidian) I think that's in the general tab).

Here's two things to try to help figure this out:

1. Check if the ink files are being created in your vault when you run the commands, even though they're not appearing in the note.

2. Try going to the files and folders tab in settings and changing the default attachment folder. Try the different folder location settings available and see if any work. 


Thank you! We'll figure this out!!

**Comment by anchoo2kewl** [comment] 2024-04-04 22:53
My version of ink: 0.1.15
Version of Obsidian: 1.5.12
I don't see any files or other assets being created in my vault!

**Comment by tripp396** [comment] 2024-04-04 22:54
I also do not see any other files added to the vault.


-
Alex
________________________________

**Comment by daledesilva** [comment] 2024-04-05 02:01
Thanks all. Anyone who's on a laptop or desktop, could you please open dev tools (in chrome it's cmd+shift+j).

Then please try the insert hand written section and please take a screenshot of any errors that appear in the console after running that.

**Comment by ichmoimeyo** [comment] 2024-04-05 02:31
I created 2 new vaults ...
I. **myInk_0.1.0** using the original Ink 0.1.0 release
It worked flawlessly out of the box as it created an **undefined** folder automatically.
![Screenshot 2024-04-04 15 56 29](https://github.com/daledesilva/obsidian_ink/assets/33708734/471ae72e-6ffe-4c29-86c8-7c8b2401ad18)


II. **myInk_0.1.15** using the Ink 0.1.15 release
Out of the box it did not work at all because no attachment folder is created automatically
![Screenshot 2024-04-04 15 42 59](https://github.com/daledesilva/obsidian_ink/assets/33708734/e579faa1-c462-48a8-9176-c126df880f2d)
I changed ...
Default location for **new attachments** 
... in the folder specified below: 
... Attachment folder path: **myInkFolder**
and it worked correctly
![Screenshot 2024-04-04 15 57 53](https://github.com/daledesilva/obsidian_ink/assets/33708734/f4f6778b-b70d-4093-b678-8b7d0ec556e1)
I changed ...
Default location for **new attachments** 
... **same folder as current file**
BUT **instead** ...
... a **new folder** called **"Ink"** was created that was <mark>not in the "new Folder"</mark>
![Screenshot 2024-04-04 16 09 39](https://github.com/daledesilva/obsidian_ink/assets/33708734/d7310236-0c0f-445a-859c-ae2e67003d6d)
I changed ...
Default location for **new attachments** 
... **in subfolder under current folder**
BUT Obsidian **didn't let me change the setting, instead** ...
... it used the same **"Ink"** folder created earlier.(i.e. **<mark>not in the "new Folder 2"</mark>**)
![Screenshot 2024-04-04 16 19 13](https://github.com/daledesilva/obsidian_ink/assets/33708734/f8d72a3e-63ea-4c94-9272-02b06f811c59)
I changed ...
Default location for new attachments changed back to ...
... in the folder specified below: myInkFolder
![Screenshot 2024-04-04 16 23 58](https://github.com/daledesilva/obsidian_ink/assets/33708734/a6534cda-2454-425f-b672-9b6e1ecc687f)

\\\\

So I guess, that as opposed to release 0.1.0, in release 0.1.15 no "undefined"folder is created automatically and one has to set/verify the default location for Ink to work :)

**Comment by anchoo2kewl** [comment] 2024-04-05 16:48
Works for me as well!

**Comment by daledesilva** [comment] 2024-04-06 00:47
Thanks for all the trials @ichmoimeyo !! And thanks for following up to verify @tripp396 and @anchoo2kewl 
I've figured out what the issue is. I added in a check if the attachment folder path included './' but it seems that if you've never changed the attachment folder before then obsidian reports it as an undefined object... so previously it created a folder called undefined, but now since I try and check the text in the path, the error occurs.

This is an easy fix so I'm doing it now.
I'll have a look into the "same folder as file" stuff too.

As a side note, the folder 'Ink' will always be created. This is so that the plugin can create extra files if needed and always keep them organised and separate from other attachments or files.

**Comment by daledesilva** [comment] 2024-04-06 05:55
Okay... These issues should be fixed in 0.1.172
Please confirm once updated :)

**Comment by ichmoimeyo** [comment] 2024-04-06 11:47
Thanks :) 
All working correctly in accordance with `Default location for new attachments`

Default location for **new attachments**
(default): **Vault folder**
... a **new folder** called "**Ink**" was created
![Screenshot 2024-04-06 01 31 31](https://github.com/daledesilva/obsidian_ink/assets/33708734/a3d46dd0-6f41-4fef-8835-67e8709b40f6)
Default location for **new attachments** 
... **in the folder specified below**: 
... Attachment folder path: **attachments**
![Screenshot 2024-04-06 01 38 00](https://github.com/daledesilva/obsidian_ink/assets/33708734/f77262ed-b616-4290-87d5-32131b7f1d4d)
Default location for **new attachments** 
... **Same folder as current file** 
![Screenshot 2024-04-06 01 40 26](https://github.com/daledesilva/obsidian_ink/assets/33708734/d52aeff6-2cd0-4ead-a3d1-8a8dca81c87b)
Default location for **new attachments**
... **in subfolder under current folder**
... Subfolder name: **attachments**
![Screenshot 2024-04-06 01 42 23](https://github.com/daledesilva/obsidian_ink/assets/33708734/4f13e3ab-0fe6-4202-98aa-1db56cafd352)

**Comment by daledesilva** [comment] 2024-04-06 13:22
Thanks for testing thoroughly

**Closed** 2024-04-06 13:22 UTC
