### ISSUE TITLE
Use Ink with pandoc | embed drawing/writing or export as image?

### ISSUE THREAD

**Issue by tobias0409** [daledesilva/obsidian_ink#51] opened 2024-06-04 19:36 UTC
Hey, I use pandoc to export the markdown file to a nice looking PDF.

Unfortunately, 

1. It is not possible to embed the "Drawings" or "Writings" and then export those -> will just shown as codeblocks
2. I cant find a way to export the drawing as svg/png and embed those.  As far as I know in a previous version there was always a .png file

Is there a way to achive the result I wish? 

Edit: For example Excalidraw for obsidian has a auto-export feature, which automatically creates an svg/png export of the file and keeps it updated, when a change is made. 

![grafik](https://github.com/daledesilva/obsidian_ink/assets/57797397/1628384a-0126-4dd5-a789-9a24607eddb5)

**Comment by tobias0409** [comment] 2024-06-05 09:41
Thanks for your fast answer! :)

You're right, if I export using the standard Obsidian "Export to PDF..." option, everything works perfectly. I'm looking forward to the export feature!

Here some additions to it, but not that important:

However, if I use Pandoc as my Markdown to PDF converter, it doesn't work properly. The issue is that Pandoc converts the Markdown to LaTeX and then LaTeX to PDF (as far as I know, also new to Pandoc), which causes Pandoc to transform code blocks into code listings. Here's an example:

![grafik](https://github.com/daledesilva/obsidian_ink/assets/57797397/215b8575-12f9-47a5-96d4-445496e606b6)

Also, I would like to upload notes with handwritten parts to my web server, which only supports Markdown files. Since the server doesn't support the Obsidian plugin, it can't display the handwritten parts correctly.

Regarding the code block embed issue: I noticed you want to avoid this so the embedded drawings/writings still work. Before using Obsidian, I used Joplin, which employs js-draw. The export to Pandoc/web server worked nicely with Joplin because it uses real .svg files. The embedded .svg has a button to click for editing. Here’s a short demo: it's essentially an embedded .svg that you can edit by clicking a button. Maybe this approach can help.

https://github.com/daledesilva/obsidian_ink/assets/57797397/5353c6c4-c989-4b9e-9b79-daa493f35eed

**Comment by daledesilva** [comment] 2024-07-27 09:22
Related/Duplicate of #31

**Closed by daledesilva** 2024-07-27 09:22 UTC
Labels: question / thought
