### ISSUE TITLE
If there is a plugin conflict, it will cause the button to malfunction when switching the reading/editing mode.

### ISSUE THREAD

**Issue by wopanda** [daledesilva/obsidian_ink#3] opened 2024-03-31 08:13 UTC
When I click the edit button and want to switch between reading/editing modes, there will be no response.

**Comment by daledesilva** [comment] 2024-04-01 08:36
Thank you for translating your issue. I had run it through Google translate myself but hadn't had time to reply.
I've uploaded a video below that I think is the action you're talking about, however, I can't reproduce the issue.

https://github.com/daledesilva/obsidian_ink/assets/18710973/61c3497f-5f8d-4484-831a-1305d6c5d036

Could you please clarify?
Please also let me know the Device Type, Operating System and the Obsidian version.

Note: I use a program called Kap to record quick and easy videos, if you can record one yourself of the issue that would be great. Kap is for Mac but there are others (like loom) for Windows.

**Comment by wopanda** [comment] 2024-04-01 10:15
Hello, thank you for your response. In the video, I performed the following actions:
When demonstrating the operation of your video, clicking the edit/read button posed no issues.

1、However, upon using the shortcut ctrl+E to switch, I noticed that many shortcuts were unresponsive, such as ctrl+P.
2、Subsequently, I clicked on the control bar ctrl+shift+i and encountered some red prompts.
3、This issue is likely caused by conflicts. Upon testing it in the Obsidian Sandbox, I did not encounter such a problem.

I am still working on determining the cause.

Windows system
Current version of Obsidian: v1.5.11



https://github.com/daledesilva/obsidian_ink/assets/61578085/b247c84a-188f-44e5-9d16-0171ee89983d

**Comment by wopanda** [comment] 2024-04-01 10:26
I think I have found the reason, the collision is caused by the kanban plugin, the specific information is as follows:

plugin:obsidian-kanban:77 Uncaught TypeError: Cannot read properties of undefined (reading 'getActiveViewOfType')
at e.eval (plugin:obsidian-kanban:77:14317)
at e.o [as executeCommand] (plugin:obsidian-kanban:23:77313)
at e.onTrigger (app.js:1:1165525)
at e.handleKey (app.js:1:757929)
at e.handleKey (app.js:1:758042)
at t.handleKey (app.js:1:758251)
at e.onKeyEvent (app.js:1:759185)
eval @ plugin:obsidian-kanban:77
o @ plugin:obsidian-kanban:23
e.onTrigger @ app.js:1
e.handleKey @ app.js:1
e.handleKey @ app.js:1
t.handleKey @ app.js:1
e.onKeyEvent @ app.js:1

**Comment by wopanda** [comment] 2024-04-02 09:43
Is there a solution to this problem?

**Comment by daledesilva** [comment] 2024-04-02 12:32
I haven’t had a chance to look into it yet. It’s possible it’s on kanbans end, but I'll figure out what's causing it.

**Comment by daledesilva** [comment] 2024-04-03 11:30
I've reproduced this problem.
Very strange.

I'm looking into it.

**Comment by daledesilva** [comment] 2024-04-04 07:11
I believe this should be fixed now.
Please update and let me know if there are further issues.

Turns out it was an issue internal to the tldraw framework. Updating the framework seems to have fixed it.

Updating:
Brat supposedly updates plugins on startup, so try starting Obsidian, give it a minute to update, then close and restart obsidian again. Check that Ink is now 1.15 or higher.

If it hasn't updated that way, you may have to uninstall it through BRAT and the normal plugin area and then install it with BRAT again.

**Closed** 2024-04-06 05:56 UTC
