### ISSUE TITLE
When Using the ink, I can't open other notes unless reloading obsidian.

### ISSUE THREAD

**Issue by rabby0101** [daledesilva/obsidian_ink#5] opened 2024-03-31 18:46 UTC
I am facing this weird bug, when I'm using the ink , after that, if I want to open any existing note, it does nothing. It just opening a new blank tab.

**Comment by daledesilva** [comment] 2024-03-31 23:25
Oh, wow. I'll have a look when I get a chance.

Can you try disabling the plug-in and see if it still occurs.
If so, try enabling it again but in the plugins settings, disable both handwriting and drawing and see if you can reproduce that way too.

Also, what's your device and obsidian version?

**Comment by RvBjx** [comment] 2024-04-01 13:54
I'm having the same issue.

Even with only "Writing" enabled I can't open any files, if I click "open in new tab" the following error is displayed:
> Cannot read properties of undefined (reading 'get cache')

**Comment by RvBjx** [comment] 2024-04-01 14:00
If I disable the plugin (without restarting Obsidian or reloading anything else) the error persists.
If I disable the plugin (with restarting Obsidian ) the error goes away.
If I disable the writing and drawing functions in the Ink settings, I can still edit already existing drawings, after editing the error will persist.

**Comment by oyes77** [comment] 2024-04-01 22:42
Came here to report the same issue on mobile.

**Comment by daledesilva** [comment] 2024-04-02 02:21
Thanks for reporting everyone. Sorry it's so broken for you.can I ask you all what **device types**, **operating systems**, and **obsidian versions** your on?

**Comment by rabby0101** [comment] 2024-04-02 11:27
- Ipad OS : Version  17.4 - Obsidian: 1.5.11 - Device : iPad Pro 2018

- MacOS: Sonoma 14.4 - Obsidian : 1.5.12 - Device : MacbookPro 2020 

- Windows : Windows 11 - Obsidian :  1.5.11      - Device : AMD Ryzen 7 + Nvidia 3060

**Comment by rabby0101** [comment] 2024-04-02 14:17
![Screenshot 2024-04-02 161500](https://github.com/daledesilva/obsidian_ink/assets/29745113/f5ff8084-9190-435b-b95e-c54e62d5109a)
Here is a list of plugins I have right now..

**Comment by rabby0101** [comment] 2024-04-02 14:29
> ![Screenshot 2024-04-02 161500](https://private-user-images.githubusercontent.com/29745113/318815520-f5ff8084-9190-435b-b95e-c54e62d5109a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjgxNTQsIm5iZiI6MTcxMjA2Nzg1NCwicGF0aCI6Ii8yOTc0NTExMy8zMTg4MTU1MjAtZjVmZjgwODQtOTE5MC00MzViLWI5NWUtYzU0ZTYyZDUxMDlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE0MjQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYjc0MjMyYTAyZDVjYjFjMWM4MGRiZGE1NjBmNWI4MmIzMTcwMTU3ZDU4MzkyOTUyN2ZkOWVmY2YzYmY4NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YyZycAdsyECkUxIENR-DLJMmB12dbIDIGupK9wOjtIo) Here is a list of plugins I have right now..

Nah, you are right probably. there could be one or some conflicting plugins that causing the issue. Right now I have this plugins and the problem has gone. but when I was facing the issue, there were a lot of plugins installed. I can't point out which one was the culprit.

**Comment by RvBjx** [comment] 2024-04-02 17:54
Here's a screen shot. I will try to deactivate the plugins me and rabby0101 have in common and comment here again with results.
<img width="167" alt="Screenshot 2024-04-02 195339" src="https://github.com/daledesilva/obsidian_ink/assets/87993060/d2a13d40-76ce-4485-8d92-29aa6db1d218">

**Comment by RvBjx** [comment] 2024-04-02 18:18
It seems to be connected to **a plugin called "DB Folder"** which I use to display my notes in database form. Without that plugin the error goes away after reloading obsidian.

**Comment by fredjoe7** [comment] 2024-04-03 04:36
i dont have the DB folder plugin, still i got the same problem

here is the list of my plugins enabled

![image](https://github.com/daledesilva/obsidian_ink/assets/107930196/c42ab93f-0fd6-43d9-bd32-083514ba4c1a)

**Comment by fredjoe7** [comment] 2024-04-03 04:42
i looked into the console while pressing control + N to create new tab which was failing in when i use ink embed..

for me its the hover editor plugin ,
![image](https://github.com/daledesilva/obsidian_ink/assets/107930196/01f99865-18d2-42e4-8e06-922c6cf25757)


after disabling the hover editor plugin, pressing control + N seems to work normally while having ink handwritten embeds

**Comment by daledesilva** [comment] 2024-04-03 13:36
I've been able to reproduce this with DB Folder. Looking into the solution now

**Comment by daledesilva** [comment] 2024-04-04 07:11
I believe this should be fixed now.
Please update and let me know if there are further issues.

Turns out it was an issue internal to the tldraw framework. Updating the framework seems to have fixed it.

Updating:
Brat supposedly updates plugins on startup, so try starting Obsidian, give it a minute to update, then close and restart obsidian again. Check that Ink is now 1.15 or higher.

If it hasn't updated that way, you may have to uninstall it through BRAT and the normal plugin area and then install it with BRAT again.

**Comment by daledesilva** [comment] 2024-04-06 05:56
Closing this... let me know if the issue is still persisting.

**Closed by daledesilva** 2024-04-06 05:56 UTC
